### ISSUE TITLE
MRELauncher doesn't see compiler

### ISSUE THREAD

**Issue by albert-tomanek** [raspiduino/mre-sdk#8]
Hi, I installed the `MRE_SDK_3.0.00.20_Normal_Eng.zip` program on my computer.  
I also have VS2008 Pro and ADS 1.2 installed and they both work.

![image](https://github.com/raspiduino/mre-sdk/assets/17899849/142e69ff-83ad-4188-9b2f-73a5a4c2b385)

But when I run MRELauncher.exe, the options to open config or to build a project are greyed out:

![image](https://github.com/raspiduino/mre-sdk/assets/17899849/a02fd314-44e2-4545-805b-4e97d3ec7a96)

And the toolbar in Visual Studio is empty:

![image](https://github.com/raspiduino/mre-sdk/assets/17899849/6c7be2ec-c555-4e5e-8e0f-3f131d47070d)

Do you have any idea how I could fix this? There were no options I could change in the installer...

**Comment by raspiduino** [comment]
Hello! Did you load the project?
![image](https://github.com/raspiduino/mre-sdk/assets/68118236/c2e1ba8d-e462-4726-919a-fbf6b374e9d6)

You can load the project by clicking the load button on the right top. If you haven't create a project, you can create it by using the <kbd>+</kbd> button.

**Comment by albert-tomanek** [comment]
Ahh that helped, thanks! I had DPI scaling turned on which caused the window to clip and I couldn't see the open button.

**Comment by raspiduino** [comment]
You are welcome. Happy developing!
